apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - target:
      kind: Node
    patch: |-
      apiVersion: v1
      kind: Node
      metadata:
        name: dummy
        annotations:
          # Forces Argo CD to use Server-Side Apply for all target nodes
          argocd.argoproj.io/sync-options: ServerSideApply=true
        labels:
          node-role.kubernetes.io/infra: ""
