apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../../base/network/kubernetes-nmstate-operator/setup/

components:
  - ../../../../../base/fundamental-building-blocks/operator/infra-nodeselector-and-tolerations/