apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../fundamental-building-blocks/operator/generic

configMapGenerator:
  - name: operator-parameters
    options:
      disableNameSuffixHash: true
      annotations:
        # Prevents this ConfigMap from being applied to the cluster
        config.kubernetes.io/local-config: "true"
    literals:
      - namespace=open-cluster-management
      - SubscriptionName=advanced-cluster-management
      - OperatorGroupName=advanced-cluster-management
      - channel=release-2.17
      - source=redhat-operators
      - installPlanApproval=Automatic
