apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# References the compiled release manifest directly from the official repository
resources:
  - namespace.yaml
  - https://github.com/bitnami/sealed-secrets/releases/download/v0.38.4/controller.yaml

# Sets the naming prefix for generated key pair secrets
patches:
  # 1. Strategic Merge Patch: Sets the naming prefix for generated key pair secrets
  - target:
      kind: Deployment
      name: sealed-secrets-controller
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: sealed-secrets-controller
      spec:
        template:
          spec:
            containers:
              - name: sealed-secrets-controller
                command:
                  - controller
                  - --key-prefix=sealed-secrets-key

# 2. JSON6902 Patch: Replaces securityContext blocks to comply with OpenShift SCC
  - target:
      kind: Deployment
      name: sealed-secrets-controller
    patch: |-
      - op: replace
        path: /spec/template/spec/securityContext
        value:
          runAsNonRoot: true
      - op: replace
        path: /spec/template/spec/containers/0/securityContext
        value:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          capabilities:
            drop:
              - ALL
