apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../fundamental-building-blocks/operator/generic

configMapGenerator:
  - name: operator-parameters
    options:
      disableNameSuffixHash: true
      annotations:
        # Prevents this ConfigMap from being applied to the cluster
        config.kubernetes.io/local-config: "true"
    literals:
      - namespace=openshift-nmstate
      - SubscriptionName=kubernetes-nmstate-operator
      - OperatorGroupName=kubernetes-nmstate-operator
      - channel=stable
      - source=redhat-operators
      - installPlanApproval=Automatic
