apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../base/openshift-local-storage-operator/setup/

components:
  - ../../../../base/fundamental-building-blocks/subscription-infra-nodeselector-and-tolerations/