apiVersion: v1
kind: Node
metadata:
  name: hub-prod-local-worker-0.openshift.local
---
apiVersion: v1
kind: Node
metadata:
  name: hub-prod-local-worker-1.openshift.local
---
apiVersion: v1
kind: Node
metadata:
  name: hub-prod-local-worker-2.openshift.local
---
