apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../base/acm/setup/

components:
  - ../../../../base/fundamental-building-blocks/operator/infra-nodeselector-and-tolerations/
