apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../../parameters/in-cluster/nodes/infra/
  - ../../../../base/fundamental-building-blocks/node-labeler/role-infra/
