apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Overrides the target namespace globally and updates RBAC subject bindings
namespace: sealed-secrets

resources:
  - ../../../../../base/security/sealed-secrets/setup/
